# Generated by Django 4.1.7 on 2023-02-28 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="expiring_link_expiration",
        ),
        migrations.AlterField(
            model_name="image",
            name="original_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/originals/",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["png", "jpg"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="images.image",
            ),
        ),
        migrations.CreateModel(
            name="ExpiringLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("time", models.DateTimeField()),
                (
                    "seconds",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(3000),
                            django.core.validators.MinValueValidator(300),
                        ]
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="images.image"
                    ),
                ),
            ],
        ),
    ]
